### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by Shmuel83**
Translate english to French (I'm french native)
Tested on my smartphone

### CODE REVIEW

**Comment by eladnava** [comment]
Hi @Shmuel83,
This is simply awesome!

Thanks so much for taking the time to translate the entire app to French! 😄 💯 

I'm sure a lot of French speakers living in Israel would appreciate it.

**Comment by eladnava** [comment]
Published to Google Play. 👍

**Comment by eladnava** [comment]
I have listed you in the Special Thanks section of the project:
> Thanks to Rodolphe Moulin for the French translation

Good?

**Comment by Shmuel83** [comment]
Thank you for your "Special Thanks" and published on Google Play.
You are very fast !

**Comment by eladnava** [comment]
My pleasure, thank you, really. 👍

**Pull request merged**
